Iter13
casnerano/go-url-shortener pull request #29
Opened 2023-01-07 16:50 UTC by casnerano

2023-01-08 20:43 UTC, ASPecherkin requested changes
есть несколько незначительных замечаний, думаю их можно будет быстро поправить и работа будет принята

2023-01-08 20:43 UTC, ASPecherkin commented on internal/app/handler/short_url.go
> +	uuid, ok := ctxUUID.(string)
молодец, что делаешь проверку типов - это спасает тебя от паники и позваоляет правильно обрабаывать такой случай

2023-01-08 20:43 UTC, ASPecherkin commented on internal/app/handler/short_url.go
> +	resultHistory := []resultURLItem{}
лучше использовать идиоматичную для Go запись создания контейнера 
особенно, если у тебя заранее известен размер 
```go
resultHistory := make(]resultURLItem, 0, len(userURLHistory))
```

2023-01-08 20:43 UTC, ASPecherkin commented on internal/app/handler/short_url.go
> +	} else {
этот else можно опустить, так как у тебя во всех случаях выше есть return

2023-01-08 20:43 UTC, ASPecherkin commented on internal/app/handler/short_url.go
> +		w.WriteHeader(http.StatusCreated)
здесь тоже можно опустить

2023-01-09 07:38 UTC, casnerano commented on internal/app/handler/short_url.go
> +	resultHistory := []resultURLItem{}
спасибо, поправил

2023-01-09 07:41 UTC, casnerano commented on internal/app/handler/short_url.go
> +	} else {
Если убрать это условие,  то код пойдет дальше на выполнение, и в результате будет попытка записи в врайтер, что скорее-всего вызовет панику, т.к. shortURLModel - будет nil, т.к. была вызвана ошибка.

```
fmt.Fprint(w, s.buildAbsoluteShortURL(shortURLModel.Code))
```

```
	if err != nil {
		// Если ошибка связана с существованием записи, то
		// устанавливает http-статус 409,
		// и пытаемся сделать выборку существующей записи
		if errors.Is(err, repository.ErrURLExist) {
			w.WriteHeader(http.StatusConflict)
			shortURLModel, err = s.urlService.GetByUserUUIDAndOriginal(uuid, urlOriginal)
			// Если не удалось сделать выборку - возвращаем 500-ую ошибку
			if err != nil {
				s.httpJSONError(w, err.Error(), http.StatusInternalServerError)
				return
			}
		} else { // Если это другая ошибка, то также возвращаем 500-ую ошибку
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	} else {
		w.WriteHeader(http.StatusCreated)
	}
```

2023-01-09 07:43 UTC, casnerano commented on internal/app/handler/short_url.go
> +	} else {
Честно говоря я планировал отрефакторить этот код, чтобы было меньше сложных условий, и также избавиться от дублирования этого кода из двух хендлеров.

2023-01-09 13:04 UTC, casnerano commented on internal/app/handler/short_url.go
> +	} else {
Прости, я подумал ты про другой else имеешь ввиду.

Этот else 
```
else {
		w.WriteHeader(http.StatusCreated)
	}
	```
	
	тоже не получится убрать, т.к. ренурн не всегда может сработать: 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/46101935/211314508-4731059c-6625-4689-94cc-593c46e32fe4.png">

2023-01-10 23:08 UTC, ASPecherkin approved these changes
со всеми замечаниями разобрались , принимаю работу

2023-01-10 23:08 UTC, ASPecherkin commented on internal/app/handler/short_url.go
> +	} else {
спасибо, что объяснил так подробно 
теерь стало понятно
по github порой сложно понять все ветви прохождения кода

2023-01-11 05:58 UTC, merged