Iter22
casnerano/go-url-shortener pull request #38
Opened 2023-04-04 22:08 UTC by casnerano

2023-04-05 17:14 UTC, kilchik requested changes

2023-04-05 17:14 UTC, kilchik commented on cmd/shortener/main.go
> +	<-ctx.Done()
По сигналу необходимо также корректно завершить все фоновые работы, у тебя это - горутина, в которой выполняется CleanOlderShortURL

2023-04-05 19:20 UTC, casnerano commented on cmd/shortener/main.go
> +	<-ctx.Done()
Спасибо! пофиксил

2023-04-06 18:39 UTC, kilchik commented on cmd/shortener/main.go
> +	<-ctx.Done()
Не до конца :) Сейчас по сигналу главная горутина завершится, не дожидаясь, пока CleanOlderShortURL обработает сигнал из контекста. Тебе нужно добавить ожидание завершения горутины с CleanOlderShortURL в главной горутине

2023-04-06 18:39 UTC, kilchik approved these changes

2023-04-13 08:38 UTC, merged